server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable-account-db
    driver-class-name: org.postgresql.Driver


# stripe:
#   api:
#     secret: ${STRIPE_API_KEY:kjfiosenweiocnioncodsnoicnc}
#   webhook:
#     secret: ${STRIPE_WEBHOOK_SECRET:web_jfdlfjlsflkdsjldjfldfj}

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/account_db
    username: account_user
    password: ${DB_PASSWORD}


stripe:
  api:
    secret: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
